apiVersion: v1
kind: Pod
metadata:
  name: pod-quota2
  namespace: quotas
spec:
  containers:
  - name: quota-container2
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "1000m"
      requests:
        memory: "600Mi"
        cpu: "350m"
