apiVersion: v1
kind: Pod
metadata:
  name: pod-run-as-non-root
spec:
  containers:
  - name: main
    image: gcr.io/google-samples/node-hello:1.0
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsNonRoot: true
