apiVersion: v1
kind: Pod
metadata:
  name: pod-run-as-user-group
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
