kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-role-binding
  namespace: dev
subjects:
- kind: User
  name: john
  apiGroup: ""
roleRef:
  kind: Role
  name: dev-role
  apiGroup: ""
