apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
      
#
# First create a pv with the pv-volume.yaml manifest on your node
#
# Create the pvc
# kubectl create -f pv-claim.yaml
#
# Verify the first-pv-volume status
# kubectl get pv first-pv-volume
#
# Verify the pvc
# kubectl get pvc first-pv-claim
#
