apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    
#    
# Create the pv
# kubectl create -f pv-volume.yaml
#
# View information about the pv
# kubectl get pv first-pv-volume
#
